{{- if .Values.storageClass  }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-basic
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.storageclass.default | quote }}
provisioner: netapp.io/trident
parameters:
  backendType: "ontap-nas"
{{- end }}