apiVersion: v1
kind: Secret
metadata:
  name: trident-backend
  namespace: trident
type: Opaque
stringData:
  backend.json: |-
    {
      "version": {{ .Values.backend.version }},
      "storageDriverName": {{ .Values.backend.storageDriverName }},
      "backendName": {{ .Values.backend.backendName }},
      "managementLIF": {{ .Values.backend.managementLIF }},
      "dataLIF": {{ .Values.backend.dataLIF }},
      "svm": {{ .Values.backend.svm }},
      "username": {{ .Values.backend.username }},
      "password": {{ .Values.backend.password }},
      "defaults": {
        "exportPolicy": "trident"
      }
    }
